version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Map port 8080 on the host to port 80 in the container
    environment:
      - NODE_ENV=production
